
#pragma once

constexpr uint8_t NUM_PLAYLISTS {99}

const char* playlist_names[] = {
    "A Tribe Calle...",
    "Architecture ...",
    "  Arcade Fire   ",
    "Arts and Crafts ",
    "  Asylum Party  ",
    "    Bachata     ",
    "  Bad Religion  ",
    "   Beach Boys   ",
    "     Beirut     ",
    "   Billy Joel   ",
    "     Bjork      ",
    "Broken Social...",
    "  Busta Rhymes  ",
    "Capos Are Indie ",
    "Catalonia Inv...",
    "Clash City Ro...",
    "Climatewave a...",
    " Cocteau Twins  ",
    "    Coldwave    ",
    "Crack Rock St...",
    "Crystal Castles ",
    "    Darkwave    ",
    "      DDT       ",
    " Dead Can Dance ",
    "   Dead Prez    ",
    "  Depeche Mode  ",
    "Disco Flies B...",
    " D_cima V_ctima ",
    "D_pe 80s Tracks ",
    "D_pe 90s Danc...",
    "Echo and The ...",
    "El _ltimo Vecino",
    " Elliott Smith  ",
    "   Elton John   ",
    " Elvis Costello ",
    "Frank _Just F...",
    "   Gary Numan   ",
    "      Goth      ",
    " Greek, Alt NOS ",
    "Greek, Folk_P...",
    "Guided By Voices",
    " Gustavo Cerati ",
    " In The Heights ",
    "   Indie Pop    ",
    "    Interpol    ",
    "Johnny F----n...",
    "  Joy Division  ",
    "    K-The-I     ",
    "    KAITOY_A    ",
    "    KRS-One     ",
    "     Keane      ",
    "    Ladytron    ",
    "  Little Nemo   ",
    "    Lowlife     ",
    "    MF Doom     ",
    "     Metric     ",
    "Mitropanos Mania",
    "   Morrissey    ",
    "My Bloody Val...",
    "      NOFX      ",
    "   New Order    ",
    "  Nicki Minaj   ",
    "   Party Jams   ",
    "  Peter Murphy  ",
    "   Peter Tosh   ",
    "      REM       ",
    "     Rakim      ",
    "     Rancid     ",
    "  Reading Time  ",
    "      Ride      ",
    "Sad Lovers an...",
    "Say Hi _To Yo...",
    "Shoegaze Spac...",
    "Silvio Rodriguez",
    "  Soda Stereo   ",
    "The Alternative ",
    " The Chameleons ",
    "   The Church   ",
    "    The Coup    ",
    "The Divine Co...",
    "The Lawrence ...",
    " The Left Banke ",
    "The Magnetic ...",
    "  The National  ",
    "   The Police   ",
    "The Psychedel...",
    "  The Strokes   ",
    "They Might Be...",
    "Tokyo Police ...",
    "Travlin Music...",
    "       U2       ",
    "Wu-Tang Killa...",
    "  Young Galaxy  ",
    "  _the beatles  ",
    "_belle and se...",
    "  _the smiths   ",
    "_cure_radiohead ",
    "_pixies_stars...",
    "    _sd misc    "
};

constexpr uint8_t playlist_lengths[] = {
    23,
    23,
    25,
    25,
    23,
    18,
    39,
    13,
    15,
    28,
    18,
    43,
    19,
    122,
    7,
    26,
    232,
    21,
    57,
    118,
    20,
    51,
    35,
    12,
    33,
    19,
    14,
    21,
    37,
    17,
    22,
    18,
    14,
    16,
    47,
    14,
    20,
    120,
    9,
    25,
    30,
    25,
    25,
    41,
    15,
    18,
    18,
    12,
    33,
    62,
    23,
    28,
    22,
    33,
    12,
    32,
    31,
    51,
    11,
    31,
    22,
    21,
    73,
    12,
    17,
    27,
    23,
    22,
    47,
    14,
    23,
    34,
    57,
    13,
    49,
    201,
    17,
    22,
    18,
    21,
    15,
    9,
    85,
    27,
    17,
    20,
    21,
    13,
    24,
    84,
    28,
    45,
    18,
    117,
    110,
    65,
    121,
    163,
    233
};

